Update for kalliope 0.5.0
kalliope-project/kalliope_starter_de pull request #3
Opened 2018-02-11 17:15 UTC by andweber

- added support for Kalliope 0.5.0
- ship "Computer" as additional, better supported trigger
- updated Readme
- fixed spell error in clock answer template
- added Makefiletemplate for deplaying to rpi

2018-02-11 19:26 UTC, Sispheor requested changes

2018-02-11 19:26 UTC, Sispheor commented on settings.yml
>  # ---------------------------
everything related to GPIO can be removed.

2018-02-11 19:26 UTC, Sispheor commented on settings.yml
>  # ---------------------------
Default Synapse section too

2018-02-11 23:20 UTC, LaMonF approved these changes

2018-02-12 10:21 UTC, merged

2018-02-12 10:21 UTC, Sispheor commented
thx